### PR TITLE
Added Windows installation script

### PR DESCRIPTION
**Pull request by aviaryan**
Added install.bat which will copy music_downloader.py to `C:/Users/UserName/music_downloader` folder and add the directory to PATH. I have tested it and it should be good to merge but there is one issue. 
setx command supports only upto 1024 characters so if a user's PATH is long in length, the script wont be able to add to PATH. But this should happen in very few cases. I personally have a lot of compilers/stuff added to PATH but still its length is around 900 characters.
You decide.

### CODE REVIEW

**Comment by yask123** [comment]
Thanks! The script is awesome! :smiley: 

About the path length, can we calculate path length?, and if it is greater than `1024` display error or something?

Also, after this gets merged, we would need to create an `issue` and warn users about this in `readme` file.

**Comment by aviaryan** [comment]
Sure. Now this script warns user when PATH exceeds 1024 chars and then quits.
Let me know if you want me to create the issue.

**Comment by yask123** [comment]
The script is super awesome! :smile:
Just tested it.
Thanks!

**Comment by aviaryan** [comment]
Glad it worked out. I had a really tough time understanding the language :cry:

**Comment by aviaryan** [comment]
PS - You may want to merge #20 now.
music_downloader_is_batch

**Comment by bendtherules** [comment]
This is not the recommended way of installing cli files in windows.

Proper way is to use "console_scripts" entry point in setup.py which both copies the script and a exe for the same to python_dir/scripts, which should be in the PATH of most people, as it is the standard installation option.

For some clues, we recently implemented this for Pontoon, look at the setup.py here - https://github.com/bendtherules/pontoon/blob/master/setup.py . Also with a little googling, you can definitely move to this better option.

**Comment by aviaryan** [comment]
I just noticed pip installing instantmusic doesn't work on Windows and opened an issue for the same.
#44

**Pull request merged**
