### PR TITLE
Added parsing for command-line arguments

### PR DESCRIPTION
**Pull request by mondayrain**
Now we can run it straight from the command-line! :)
instantmusic-singlesong

I also added some standard flags and their functionality:

-h for help
instantmusic-help

-l for passing a list of songs, delimited by a comma
instantmusic-list

-p for turning off (y/n) prompts and -q for quiet mode so you can run it in the background, in case you want to pass in a file with -f
instantmusic-file

### CODE REVIEW

**Comment by yask123** [comment]
Thanks for helping out :smile: !
Can you help me solve these` conflicts` ? , I recently merged a PR.

**Comment by mondayrain** [comment]
@yask123 Fixed merge conflicts, fixed some bugs while I was add it :)
Not sure why Travis-CI build is failing, but I'm guessing because there's no actual proper .yaml file?

**Comment by yask123** [comment]
Whoops, forgot to add `.yaml` file. Try again.

**Comment by mondayrain** [comment]
Done! :D

**Pull request merged**
