### PR TITLE
Implement issue #55 - added argument to launch a program

### PR DESCRIPTION
**Pull request by mlterpstra92**
This commit enables the user to pass a program to instantmusic and causes the downloaded
song to play in this program as it is finished downloading.

### CODE REVIEW

**Comment by yask123** [comment]
Thanks for helping out :smile: 
Hey, few files were changed after you sent this PR.
Can you help me fix conflicts?

**Comment by mlterpstra92** [comment]
Hi, I've merged the files as can be seen in the commit above. I also fixed another possible bug (the number the user entered is was not necessarily in the range of possible downloadable songs) and made it more compliant with PEP8.

**Comment by yask123** [comment]
Thanks @mlterpstra92 .
There were a couple of bugs. Eg: I couldn't download the song no. [0].
Also how did you test it ?
I tried with `vlc` , and it didn't seem to work.

**Comment by mlterpstra92** [comment]
Hey @yask123 .
You were right about not being able to download song [0]. This is fixed in the latest commit. 
However, I can open the downloaded song with VLC just fine. Is the vlc binary in your path?
If so, can you test again with the latest commit, because it seems to work over here.

**Comment by yask123** [comment]
Yep, VLC isn't in my path. Perhaps we should do something like this: https://github.com/mafintosh/peerflix/blob/master/app.js#L201 ?

Sorry for late reply, college exams :|

**Pull request closed without merging**
